version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: secureVaultpg
    ports:
      - "5433:5432"  # host:container
    environment:
      POSTGRES_USER: svuser
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: securevault
    restart: "no"  # <== prevents auto-start

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    restart: "no"  # <== prevents auto-start
