logging:
  level:
    root: INFO
    com.praj: DEBUG
server:
  port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/secureApp
          jwt-set-uri: http://localhost:8080/realms/secureApp/protocol/openid-connect/certs

